
// Module included in the following assemblies:
//
// *mcp_gateway_config/mcp-gateway-register-virtual-mcp-servers.adoc

:_mod-docs-content-type: CONCEPT
[id="con-create-virt-mcp-server_{context}"]
= About virtual MCP servers

[role="_abstract"]
When you aggregate all your MCP servers centrally, you solve for authentication, authorization, and configuration management. At the same time, this aggregation can overwhelm large-language models (LLMs) and AI agents with too many tool choices. You can create virtual MCP servers to curate tools for each situation.

You can narrow the scope for your agentic services and applications by creating virtual MCP servers that filter the complete tool list based on a curated selection and access only the relevant tools with HTTP headers. You can use virtual MCP servers to accomplish the following efficiencies:

* Create specialized collections of tools for specific use cases.
* Reduce the load on LLMs by presenting fewer, more relevant tools.
* Group tools by function, for example, development tools, data analysis tools, and so on.
* Make it easier for users and agents to find the right tools.
* Combine with authorization policies for fine-grained access management.

Virtual MCP servers only filter which tools a client can discover by using the `tools/list` concept. Virtual MCP servers do not change `tools/call` routing or authorization.
