// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: CONCEPT
[id="rhcl-secure-protect-connect_{context}"]
= Secure, protect, and connect APIs

[role="_abstract"]
You can use {prodname} on {ocp} to connect an API that you expose by a applying `Gateway` object. Ingress is handled by Gateway API. You must also add a DNS provider secret, TLS and other policies to secure your connections, and use an `HTTP` route object to define the flow of traffic.

{prodname} draws on the user-role concepts of Gateway API, for example:

* *Platform engineers*: Generally in charge of {ocp} infrastructure, platform engineers create and secure `Gateway` objects with associated policies that application developers use to deploy APIs.

* *Application developers*: Application developers create the applications used on {ocp}, and can override the gateway-level global authorization and rate-limiting policies to configure application-level requirements for specific users.

//TODO these don't match gateway api; need to determine if JTBD will use roles or not