// Module included in the following assemblies:
//
// *observability/observability.adoc

:_mod-docs-content-type: CONCEPT
[id="rhcl-observability-features_{context}"]
= {prodname} observability features

[role="_abstract"]
{prodname} uses metrics exposed by {prodname} components, Gateway API state metrics, and standard metrics exposed by Envoy to build a set template dashboards and alerts. Envoy is part of {service-mesh}. In this case, it runs as a gateway deployment.

You can download and use Kuadrant community-based templates to integrate with Grafana, Prometheus, and Alertmanager deployments, or use these templates as starting points to change for your specific needs. Use the secure images available in the Red Hat Catalog at: link:https://catalog.redhat.com/en/software/containers/rhcl-1/rhcl-rhel9-operator/672a14ffb6ba8300a48c3799#get-this-image[Red Hat Connectivity Link].
// kiali not tested for this release

{prodname} includes the following observability features:

* Metrics: Prometheus metrics for monitoring gateway and policy performance.
* Tracing: Distributed tracing with Red Hat build of OpenTelemetry support for request flows.
* Access Logs: Envoy access logs with request correlation and structured logging.
* Dashboards: Pre-built Grafana dashboards for visualization.
