// Module included in the following assemblies:
//
// *introduction/introduction.adoc

:_mod-docs-content-type: CONCEPT
[id="connectivity-link-policies_{context}"]
= {prodname} policy APIs
//TODO this content belongs in deployment as concepts before procedures
[role="_abstract"]
Understand how and when you can use the {prodname} core policies and observability features with your cloud applications and APIs.

Secure your applications with `TLSPolicy`::

* `TLSPolicy` is a lightweight wrapper API to manage TLS for targeted gateways.
* Automatically provision TLS certificates based on the gateway listener hosts by using integration with `cert-manager` and ACME providers such as Let's Encrypt.
* Configure secrets so that the gateway automatically retrieves them.

Protect your applications with `AuthPolicy`::

* Use `AuthPolicy` objects to apply authentication and authorization across your selected listeners in a gateway or at the `HTTPRoute` or `HTTPRouteRule` level.
* Use the hierarchical and role-based concept of defaults and overrides to improve collaboration and ensure compliance.
* Use dedicated OIDC authentication providers such as Red Hat build of Keycloak.
* Apply fine-grained authorization requirements based on `request` and `metadata` attributes.

Protect your applications with `RateLimitPolicy`::

* Apply rate-limiting rules across all listeners in a gateway or at the `HTTPRoute` or `HTTPRouteRule` level.
* Use the role-based and hierarchical concept of defaults and overrides to improve collaboration and ensure compliance.
* Configure limits conditionally based on metadata and request data.
* Share counters by using a backend store in multicluster environments.

For example, the following rate-limiting policy configures a specified limit of 5 requests per 10 seconds for every listener defined in the target gateway that does not have its own rate limiting policy defined:

.Rate-limiting policy example
[source,yaml]
----
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: gw-rlp
spec:
  targetRef: # Specifies Gateway API policy attachment
    group: gateway.networking.k8s.io
    kind: Gateway
    name: external
  defaults: # Means it can be overridden
    limits: # Limitador component configuration
      "global":
        rates:
        - limit: 5
          window: 10s

----
//this seems out of place

Connect your applications with `DNSPolicy`::

* `DNSPolicy` is a standard API that is not based on custom annotations.
* Automatically populate DNS records based on listener hosts and addresses expressed by Gateway API resources.
* Configure multicluster connectivity and routing options, for example, geographic and weighted responses.
* Use common cloud DNS providers: Amazon Route 53, Microsoft Azure DNS, Google Cloud DNS, or CoreDNS.
* Configure health checks to enable DNS failover.

Observe your ingress traffic::

You can use the {prodname} observability features to observe and monitor your gateways, applications, and APIs on {ocp}. You can download and use community-based templates to integrate with Grafana, Prometheus, and Alertmanager deployments, or use these templates as starting points to modify for your specific needs.
