// Module included in the following assemblies:
//
// *observability/observability.adoc

:_mod-docs-content-type: CONCEPT
[id="rhcl-observability-features_{context}"]
= {prodname} observability features

[role="_abstract"]
{prodname} uses metrics exposed by {prodname} components, Gateway API state metrics, and standard metrics exposed by Envoy to build a set template dashboards and alerts.
//is envoy here just part of Service Mesh that's being used as a sidecar proxy (istio-proxy)?
You can download and use Kuadrant community-based templates to integrate with Grafana, Prometheus, and Alertmanager deployments, or use these templates as starting points to modify for your specific needs.
// do we have downstream templates instead? downloading upstream is generally not allowed in openshift downstream docs

{prodname} includes the following observability features:

* Metrics: Prometheus metrics for monitoring gateway and policy performance.
* Tracing: Distributed tracing with Red Hat build of OpenTelemetry support for request flows.
//are we using otel 3.8? see https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html-single/red_hat_build_of_opentelemetry/index#new-features-and-enhancements_otel-rn
* Access Logs: Envoy access logs with request correlation and structured logging.
* Dashboards: Pre-built Grafana dashboards for visualization.

//TODO envoy concept, prometheus, rate-limiting
