// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: CONCEPT
[id="con-about-config-gateway-policies_{context}"]
= About configuring your Gateway policies and HTTP route

[role="_abstract"]
As a platform engineer or cluster administrator, you must expose endpoints and program your HTTPS listener after you deploy your `Gateway` object. Next, take the following steps:

* Create and apply  a `TLSPolicy` custom resource (CR) that uses your `CertificateIssuer` object to set up your HTTPS listener certificates.
* Create and apply an `HTTPRoute` CR for your `Gateway` object to communicate with your backend application API.
* Create and apply an `AuthPolicy` CR to set up a default HTTP `403` response for any unprotected endpoints
* Create and apply a `RateLimitPolicy` CR to set up a default artificially low global limit to further protect any endpoints exposed by the `Gateway` object.
* Create and apply a `DNSPolicy` CR with a load balancing strategy for your `Gateway` object.

[IMPORTANT]
====
In multicluster environments, you must perform all of the steps in each cluster individually, unless specifically excluded.
====
