// Module included in the following assemblies:
//
// *introduction/introduction.adoc

:_mod-docs-content-type: CONCEPT
[id="rhcl-platform-eng-workflow_{context}"]
= Platform engineer workflow

[role="_abstract"]
As a platform engineer or infrastructure provider, you can use {prodname} to set up ingress gateways on {ocp} clusters in specific regions. You can configure all policies identically on all gateways for consistency.

For example, configure DNS policies to ensure that customers in Brazil are routed to the South American data center and so on. You can also configure TLS, authentication and authorization, and rate-limiting policies to ensure that gateway security, performance, and monitoring all conform to your standards.

Connect gateways and load balance::
As a platform engineer, you must start by creating at least one gateway. If gateways exist, you can move on to configuring policies for your gateways.

You can connect gateways by creating a DNS policy and configuring a global load balancing strategy. DNS records are reconciled with your cloud DNS provider automatically, whether in a single-cluster or multicluster environment. You can use the following features:

* Automatic DNS configuration
* Mutiple DNS providers
* DNS-based load balancing, such as round-robin, weighted, and geo-based
* Single or multicluster ready

Secure gateways::
After you create your gateways, secure them. You can secure gateways by using a TLS policy that automatically generates certificate requests for the host names specified in your gateway. You can also set up application security defaults and overrides by using authentication and authorization policies and rate-limiting policies. You can use the following features:

* TLS: Automatic certificate requests and ACME providers
* Auth policies
* Rate-limiting: Global rate-limiting, external IDPs, default and overrides

Observe gateways::
After your gateways are created and secured, you can configure your observability stack. Observe your connectivity and runtime metrics by using dashboards and alerts. For example, configure metrics for policy compliance and governance, resource consumption, error rates, request latency and throughput.
