// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: CONCEPT
[id="deploy-prerequisites_{context}"]
= Check your {prodname} installation and permissions

[role="_abstract"]
This guide expects that you have successfully installed {prodname} on at least one {ocp} cluster, and that you have the correct user permissions.
//TODO this module can probably be deleted during deployment CQA

* You completed the {prodname} installation steps on one or more clusters.
* If plan to use rate-limiting in a multicluster environment, you have installed {prodname} on more than one cluster and have a shared accessible Redis-based datastore.
* You installed the {oc-first}.
* You have write access to the {ocp} namespaces used in this guide.
* You have an AWS account with Amazon Route 53 and a DNS zone for the examples in this guide.  {prodname} also supports Google Cloud DNS and Microsoft Azure DNS.
* If you plan to use observability, you configured {ocp} user workload monitoring to remote-write to a central storage system.
