// Module included in the following assemblies:
//
// *mcp_gateway_config/mcp-gateway-register-virtual-mcp-servers.adoc

:_mod-docs-content-type: CONCEPT
[id="con-virt-mcp-server-auth-tool-filtering_{context}"]
= About virtual MCP servers authorization and tool filtering

[role="_abstract"]
If you have authentication and user-based tool filtering configured on your MCP servers, and then set up virtual MCP servers, the resulting tool list is the intersection of two filters.

The `AuthPolicy` custom resource (CR) configurations you applied when you registered the MCP servers are used. You do not need to make additional configurations when creating virtual MCP servers.

The MCP gateway broker component applies filters sequentially when handling a `tools/list` request with a virtual MCP server header. The following are the applied filters in order:

. Identity-based filtering: The `x-authorized-tools` header, injected by the `AuthPolicy` CR, reduces the tool list to only the tools that the user has `resource_access` roles configured for.
. Virtual MCP server filtering: The `X-Mcp-Virtualserver` header further reduces the available-tools list to only those tools that are defined in the `MCPVirtualServer` CR.

For example, if the `accounting` virtual server lists `test1_greet` and `test3_add`, but the user only has the `greet` role on `mcp-test/test-server1`, that user only sees the tool, `test1_greet`.
