// Module included in the following assemblies:
//
// * microshift/running_applications/microshift-deploy-with-mirror-registry.adoc

:_mod-docs-content-type: PROCEDURE
[id="microshift-downloading-container-images_{context}"]
= Downloading container images

After you have located the container list and completed the mirroring prerequisites, download the container images to a host with internet access.

.Prerequisites

* You are logged into a host with access to the internet.
* The `.pull-secret-mirror.json` file and `microshift-containers` directory contents are available locally.

.Procedure

. Install the `skopeo` tool used for copying the container images by running the following command:
+
[source,terminal]
----
$ sudo dnf install -y skopeo
----

. Set the environment variable that points to the pull secret file:
+
[source,terminal]
----
$ PULL_SECRET_FILE=~/.pull-secret-mirror.json
----

. Set the environment variable that points to the list of container images:
+
[source,terminal]
----
$ IMAGE_LIST_FILE=~/microshift-container-refs.txt
----

. Set the environment variable that points to the destination directory for storing the downloaded data:
+
[source,terminal]
----
$ IMAGE_LOCAL_DIR=~/microshift-containers
----

. Run the following script to pull the images from the original registry and mirror to your custom registry:
+
[source,terminal]
----
while read -r src_img; do
    # Remove the source registry prefix and SHA
    local dst_img
    dst_img=$(echo "${src_img}" | cut -d '/' -f 2-)
    local dst_img_no_tag
    dst_img_no_tag="${dst_img%%[@:]*}"
    # Add the target registry prefix
    dst_img="${TARGET_REGISTRY}/${dst_img}"
    dst_img_no_tag="${TARGET_REGISTRY}/${dst_img_no_tag}"

    # Mirror the image and tag it in the target registry
    echo "Mirroring '${src_img}' to '${dst_img}'"
    skopeo_retry copy --all --quiet \
        --preserve-digests \
        --authfile "${PULL_SECRET_FILE}" \
        docker://"${src_img}" docker://"${dst_img}"

    echo "Tagging '${dst_img_no_tag}' as 'latest'"
    skopeo_retry copy --all --quiet \
        --preserve-digests \
        --authfile "${PULL_SECRET_FILE}" \
        docker://"${dst_img}" docker://"${dst_img_no_tag}:latest"
done < "${IMAGE_LIST_FILE}"
----
