//Module included in the following assemblies:
//
//* microshift_running_apps/microshift-operators-olm.adoc

:_mod-docs-content-type: CONCEPT
[id="microshift-adding-OLM-Operators-to-disconnected-cluster_{context}"]
= About adding OLM-based Operators to a disconnected cluster

For Operators that are installed on disconnected clusters, Operator Lifecycle Manager (OLM) by default cannot access sources hosted on remote registries because those remote sources require full internet connectivity.  Therefore, you must mirror the remote registries to a highly available container registry.

The following steps are required to use OLM-based Operators in offline situations:

* Include OLM in your container image list for your mirror registry.
* Configure the system to use the mirror by updating your CRI-O configuration directly. `ImageContentSourcePolicy` is not supported in {microshift-short}.
* Add a `CatalogSource` object to the cluster so that the OLM catalog Operator can use the local catalog on the mirror registry.
* Ensure that {microshift-short} is installed to run in a disconnected capacity.
* Ensure that the network settings are configured to run in disconnected mode.

After enabling OLM in an offline cluster, you can continue to use your unrestricted workstation to keep your local catalog sources updated as newer versions of Operators are released.
