// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: PROCEDURE
[id="create-gateway_{context}"]
= Creating a gateway

[role="_abstract"]
As a platform engineer, create a gateway to your {ocp} cluster to set up the infrastructure used by application developers. The following example assumes that you are using the {ocp} Cluster Ingress Operator (CIO).

include::snippets/snippet-openshift-cio-gatewayclass.adoc[leveloffset=+1]

If you are using {service-mesh} on {ocp} 4.19 and newer and you set the `ISTIO_GATEWAY_CONTROLLER_NAMES` variable to `istio.io/gateway-controller` during your {prodname} installation, then you can use the `GatewayClass` custom resource (CR) created by default by {service-mesh}. Make sure you use the corresponding `spec.gatewayClassName` value in your `Gateway` CR.

.Prerequisites

* {prodname} is installed on the {ocp} cluster you are working with.
* You set the `ISTIO_GATEWAY_CONTROLLER_NAMES` environment variable value to `openshift.io/gateway-controller/v1` during your {prodname} installation.
* You created a `GatewayClass` named `openshift-default` and specified a `controllerName` of `openshift.io/gateway-controller/v1`.
* The {oc-first} is installed.
* You are logged in to the {ocp} cluster with write access to the namespaces you need to use.
* You have a DNS zone available for use.

.Procedure

* Create a gateway that uses the {ocp} CIO by running the following command:
+
[source,terminal]
----
$ oc apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${KUADRANT_GATEWAY_NAME}
  namespace: ${KUADRANT_GATEWAY_NS}
  labels:
    kuadrant.io/gateway: "true"
spec:
    gatewayClassName: openshift-default
    listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: "api.${KUADRANT_ZONE_ROOT_DOMAIN}"
      name: api
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
        - group: ""
          kind: Secret
          name: api-${KUADRANT_GATEWAY_NAME}-tls
        mode: Terminate
EOF
----
+
[IMPORTANT]
====
In a multicluster environment, for {prodname} to balance traffic by using DNS across clusters, you must specify a gateway with a shared hostname. You can define this by using an HTTPS listener with a wildcard hostname based on the root domain.
====

.Verification

. Check the status of your gateway by running the following command:
+
[source,terminal]
----
$ oc get gateway ${KUADRANT_GATEWAY_NAME} -n ${KUADRANT_GATEWAY_NS} -o=jsonpath='{.status.conditions[?(@.type=="Accepted")].message}{"\n"}{.status.conditions[?(@.type=="Programmed")].message}'
----
+
The statuses `Accepted` and `Programmed` mean that your gateway is valid and assigned an external address.

. Check the status of your HTTPS listener by running the following command:
+
[source,terminal]
----
$ oc get gateway ${KUADRANT_GATEWAY_NAME} -n ${KUADRANT_GATEWAY_NS} -o=jsonpath='{.status.listeners[0].conditions[?(@.type=="Programmed")].message}'
----

.Next steps

* Configure a TLS policy so that the The HTTPS listener can accept traffic.
