// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: PROCEDURE
[id="set-up-tls-issuer_{context}"]
= Add a TLS certificate issuer

[role="_abstract"]
To secure communication to your Gateways, you must define a certification authority as an issuer for TLS certificates.

[NOTE]
====
This example uses the Let's Encrypt TLS certificate issuer for simplicity, but you can use any certificate issuer supported by `cert-manager`. In multicluster environments, you must add your TLS issuer in each {ocp} cluster.
====

.Prerequisites

* You installed {prodname} on one or more clusters.
* If you plan to use rate-limiting in a multicluster environment, you have a shared Redis-based datastore.
* You installed the {oc-first}.
* You have write access to the {ocp} namespaces you need to work with.
* You have access to external or on-premise DNS.
* You created a gateway.
* You configured your gateway policies and `HTTP` routes.

.Procedure

. Enter the following command to define a TLS certificate issuer:
+
[source,terminal]
----
$ kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${KUADRANT_CLUSTER_ISSUER_NAME}
spec:
  selfSigned: {}
EOF
----

. Wait for the `ClusterIssuer` to become ready as follows:
+
[source,terminal]
----
$ kubectl wait clusterissuer/${KUADRANT_CLUSTER_ISSUER_NAME} --for=condition=ready=true
----
