// Module included in the following assemblies:
//
// *install-guide/disconnected-install.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-rhcl-disconnected-install-operators_{context}"]
= Installing the {prodname} operator

[role="_abstract"]
After mirroring the catalog, you can install the {prodname} operator using Operator Lifecycle Manager (OLM).

.Prerequisites

* You have mirrored the {prodname} operator catalog to your local registry
* You have applied the catalog source to your cluster

.Procedure

. Create a namespace for {prodname}:
+
[source,terminal]
----
$ oc create namespace kuadrant-system
----

. Create an `OperatorGroup` for the {prodname} operator:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kuadrant-operator-group
  namespace: kuadrant-system
spec: {}
----

. Apply the `OperatorGroup`:
+
[source,terminal]
----
$ oc apply -f operatorgroup.yaml
----

. Create a `Subscription` for the {prodname} operator:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhcl-operator
  namespace: kuadrant-system
spec:
  channel: stable <1>
  name: rhcl-operator
  source: <catalog_source_name> <2>
  sourceNamespace: openshift-marketplace
----
+
<1> Specify `stable` as the channel.
<2> Specify the name of the `CatalogSource` object created by `oc-mirror`. You can find the catalog source name by running `oc get catalogsource -n openshift-marketplace`.
+
[NOTE]
====
OLM automatically installs the Authorino, Limitador, and DNS operators based on the dependencies declared in the {prodname} operator bundle.
====

. Apply the `Subscription`:
+
[source,terminal]
----
$ oc apply -f subscription.yaml
----

.Verification

. Verify the {prodname} operator installed successfully:
+
[source,terminal]
----
$ oc get csv -n kuadrant-system
----
+
.Example output
[source,terminal]
----
NAME                           DISPLAY                  VERSION   REPLACES   PHASE
authorino-operator.vX.Y.Z      Authorino Operator       X.Y.Z                Succeeded
dns-operator.vX.Y.Z            DNS Operator             X.Y.Z                Succeeded
kuadrant-operator.vX.Y.Z       Kuadrant Operator        X.Y.Z                Succeeded
limitador-operator.vX.Y.Z      Limitador Operator       X.Y.Z                Succeeded
----

. Verify the operator pod is running:
+
[source,terminal]
----
$ oc get pods -n kuadrant-system
----
+
.Example output
[source,terminal]
----
NAME                                                READY   STATUS    RESTARTS   AGE
authorino-operator-controller-manager-<hash>        2/2     Running   0          3m
dns-operator-controller-manager-<hash>              2/2     Running   0          3m
kuadrant-operator-controller-manager-<hash>         2/2     Running   0          5m
limitador-operator-controller-manager-<hash>        2/2     Running   0          3m
----
