// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: PROCEDURE
[id="set-up-environment_{context}"]
= Set up your environment

[role="_abstract"]
This section shows how you can set up your environment variables and deploy the example Toystore application on your {ocp} cluster.
//TODO this entire procedure needs a downstream example

.Prerequisites

* {prodname} is installed on the {ocp} cluster you are working with.
* The {oc-first} is installed.
* You are logged in to the {ocp} cluster with write access to the namespaces you need to use.
* You have a DNS zone available for use.
* Optional. For rate limiting in a multicluster environment, you have installed {prodname} on more than one cluster. You also have a shared and accessible Redis-based datastore.
* Optional. For observability, {ocp} user workload monitoring is configured to remote-write to a central storage system.

.Procedure
//TODO FIXME steps, also Q: we need to define these as upstream?
. Optional: Set the following environment variables:
+
[source,terminal]
----
$ export KUADRANT_GATEWAY_NS=api-gateway \
  export KUADRANT_GATEWAY_NAME=ingress-gateway \
  export KUADRANT_DEVELOPER_NS=toystore \
  export KUADRANT_AWS_ACCESS_KEY_ID=xxxx \
  export KUADRANT_AWS_SECRET_ACCESS_KEY=xxxx \
  export KUADRANT_AWS_DNS_PUBLIC_ZONE_ID=xxxx \
  export KUADRANT_ZONE_ROOT_DOMAIN=example.com
  export KUADRANT_CLUSTER_ISSUER_NAME=self-signed
----
+
These environment variables are described as follows:
+
* `KUADRANT_GATEWAY_NS`: Namespace for your gateway in {ocp}.
* `KUADRANT_GATEWAY_NAME`: Name of your ingress gateway in {ocp}.
* `KUADRANT_DEVELOPER_NS`: Namespace for the example Toystore app in {ocp}.
* `KUADRANT_AWS_ACCESS_KEY_ID`: AWS key ID with access to manage your DNS zone.
* `KUADRANT_AWS_SECRET_ACCESS_KEY`: AWS secret access key with permissions to manage your DNS zone.
* `KUADRANT_AWS_DNS_PUBLIC_ZONE_ID`: AWS Route 53 zone ID for the Gateway. This is the ID of the hosted zone that is displayed in the AWS Route 53 console.
* `KUADRANT_ZONE_ROOT_DOMAIN`: Root domain in AWS Route 53 associated with your DNS zone ID.
* `KUADRANT_CLUSTER_ISSUER_NAME`: Name of the certificate authority or issuer TLS certificates.
+
[NOTE]
====
If you know your environment variable values, you can set up the required YAML files to suit your environment.
====
//which are? example? link?

//cannot use this, not secure
. Create the namespace for the Toystore app as follows:
+
[source,terminal]
----
$ oc create ns ${KUADRANT_DEVELOPER_NS}
----

//downstream example?
. Deploy the Toystore app to the developer namespace:
+
[source,terminal]
----
$ oc apply -f https://raw.githubusercontent.com/Kuadrant/Kuadrant-operator/main/examples/toystore/toystore.yaml -n ${KUADRANT_DEVELOPER_NS}
----
