// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: PROCEDURE
[id="set-up-dns-provider-secret_{context}"]
= Setting up a DNS provider secret

[role="_abstract"]
As a platform engineer, you can create access to the DNS zones that {prodname} can use by configuring your external DNS provider credentials. After setting up your `Secret` custom resource (CR), restrict access to only the DNS zones that you want {prodname} to manage by setting a `DNSPolicy` CR.

[IMPORTANT]
====
You must apply the following `Secret` CR to each cluster.
====

.Prerequisites

* You installed {prodname} on one or more clusters.
* You installed the {oc-first}.
* You have write access to the {ocp} namespaces you need to work with.
* You have access to external or on-premise DNS.

.Procedure

. Create the namespace you want your `Gateway` CR deployed in by running the following command:
+
[source,terminal]
----
$ oc create ns ${KUADRANT_GATEWAY_NS}
----

. Create the secret credentials in the same namespace as the gateway namespace by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc -n ${KUADRANT_GATEWAY_NS} create secret generic _<aws-credentials>_ \
  --type=kuadrant.io/aws \
  --from-literal=AWS_ACCESS_KEY_ID=$KUADRANT_AWS_ACCESS_KEY_ID \
  --from-literal=AWS_SECRET_ACCESS_KEY=$KUADRANT_AWS_SECRET_ACCESS_KEY
----
+
Replace `_<aws-credentials>_` with the secret you want to use.

.Next step

* Configure your TLS issuer and policy.
