// Module included in the following assemblies:
//
// *observability/observability.adoc

:_mod-docs-content-type: PROCEDURE
[id="configure-obs-monitoring_{context}"]
= Configure your observability monitoring stack

[role="_abstract"]
You can prepare your monitoring stack to give you insight into your gateways, applications, and APIs by setting up dashboards and alerts on your {ocp} cluster.

The example dashboards and alerts for observing {prodname} functionality use low-level CPU and network metrics from the user monitoring stack in {ocp} and resource-state metrics from Gateway API and {prodname} resources. The user monitoring stack in {ocp} is based on the https://prometheus.io/[Prometheus] open source project.
//we should probably really be shipping downstream templates with RHCL

[IMPORTANT]
====
You must perform this procedure on each {ocp} cluster that you want to use {prodname} on.
====

.Prerequisites

* You installed {prodname}.
* You set up metrics, such as `prometheus`.
* You installed and configured Grafana on your {ocp} cluster.
// The upstream site says last tested on OCP 4.17. Do we have a current test?
//* You have cloned the https://github.com/Kuadrant/kuadrant-operator[Kuadrant Operator GitHub repository].
//Q: not allowed in OCP prod docs; can we use the image as we did for the dashboard at https://catalog.redhat.com/en/software/containers/rhcl-1/rhcl-rhel9-operator/672a14ffb6ba8300a48c3799#get-this-image?

.Procedure

. Verify that user workload monitoring is configured correctly in your {ocp} cluster as follows:
+
[source,bash]
----
$ kubectl get configmap cluster-monitoring-config -n openshift-monitoring -o jsonpath='{.data.config\.yaml}'|grep enableUserWorkload
----
+
The expected output is `enableUserWorkload: true`.

. Install the {prodname}, Gateway, and Grafana component metrics and configuration as follows:
+
[source,bash]
----
$ kubectl apply -k https://github.com/Kuadrant/kuadrant-operator/config/install/configure/observability?ref=v1.2.0
----
//Q: downstream version? we don't really permit this in production docs on the OCP side

. From the root directory of your Kuadrant Operator repository, configure the {ocp} `thanos-query` instance as a data source in Grafana as follows:
+
[source,bash]
----
TOKEN="Bearer $(oc whoami -t)"
HOST="$(kubectl -n openshift-monitoring get route thanos-querier -o jsonpath='https://{.status.ingress[].host}')"
echo "TOKEN=$TOKEN" > config/observability/openshift/grafana/datasource.env
echo "HOST=$HOST" >> config/observability/openshift/grafana/datasource.env
kubectl apply -k config/observability/openshift/grafana
----

. Configure the example Grafana dashboards as follows:
+
[source,bash,subs="attributes+"]
----
$ kubectl apply -k https://github.com/Kuadrant/kuadrant-operator/examples/dashboards?ref=v{operator-version}
----
//Q: no github allowed
