// Module included in the following assemblies:
//
// *install-guide/disconnected-install.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-rhcl-disconnected-install-ts-pods-stuck_{context}"]
= Troubleshooting stuck pods in a disconnected installation

[role="_abstract"]
If your pods are stuck with an `ImagePullBackOff` status, this might mean that the image is either not in the mirror registry or that the `ImageDigestMirrorSet` object not applied correctly.
//Q: should we specify an image here?

.Prerequisites

* You completed a disconnected installation of {prodname}.

.Procedure

. Verify that `ImageDigestMirrorSet` exists by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc get imagedigestmirrorset
----

. Check whether the specific image was mirrored by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc image info _<your_mirror_registry>_/kuadrant/kuadrant-operator@sha256:_<digest>_
----
+
Replace `_<digest>_` with the complete digest value.

. Check pod events by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc describe pod _<pod_name>_ -n kuadrant-system
----
+
Replace `_<pod_name>_` with the name of the stuck pod.
