// Module included in the following assemblies:
//
// *install-guide/disconnected-install.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-rhcl-disconnected-mirror-catalog_{context}"]
= Mirroring the {prodname} operator catalog

[role="_abstract"]
You can mirror the Red Hat operator catalog containing the {prodname} operator to your disconnected environment using the `oc-mirror` plugin.

.Prerequisites

* You have installed the `oc-mirror` CLI plugin
* You have access to `registry.redhat.io` on an internet-connected workstation
* You have credentials for your mirror registry configured in `${HOME}/.docker/config.json`

.Procedure

. On your internet-connected workstation, create an `ImageSetConfiguration` file named `rhcl-imageset-config.yaml`:
+
[source,yaml,subs="attributes+"]
----
apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v{product-version} <1>
    packages:
    - name: rhcl-operator <2>
  additionalImages:
  - name: registry.redhat.io/rhcl-1/coredns-rhel9:vX.Y.Z <3>
----
+
<1> Specify the Red Hat operator catalog version matching your {ocp} cluster version.
<2> The {prodname} operator package. Dependency operators (Authorino, Limitador, DNS) are included automatically.
<3> Optional. The CoreDNS image if you plan to use the DNS Operator CoreDNS deployment feature. Replace `vX.Y.Z` with the version matching the {prodname} operator release.

. Mirror the catalog to a local directory:
+
[source,terminal]
----
$ oc mirror --v2 --config rhcl-imageset-config.yaml file://./rhcl-mirror
----
+
This command downloads the catalog and operator images to the `rhcl-mirror` directory.

. Transfer the `rhcl-mirror` directory to your disconnected environment using removable media.

. On a host in the disconnected environment with access to your mirror registry, push the images to the registry:
+
[source,terminal,subs="+quotes"]
----
$ oc mirror --v2 --config rhcl-imageset-config.yaml \
  --from file://./rhcl-mirror \
  docker://_<mirror_registry>_:_<port>_
----
+
Replace `_<mirror_registry>_` and `_<port>_` with your mirror registry details.

. Apply the `ImageDigestMirrorSet` or `ImageTagMirrorSet` to configure the cluster to use the mirrored images:
+
[source,terminal]
----
$ oc apply -f results-*/cluster-resources/idms-oc-mirror.yaml
$ oc apply -f results-*/cluster-resources/itms-oc-mirror.yaml
----

. Wait for the `MachineConfigPool` to update:
+
[source,terminal]
----
$ oc wait mcp --all --for=condition=Updated --timeout=30m
----
+
.Example output
[source,text]
----
machineconfigpool.machineconfiguration.openshift.io/master condition met
machineconfigpool.machineconfiguration.openshift.io/worker condition met
----
+
[NOTE]
====
This step restarts the kubelet on all nodes to apply the new registry configuration.
====

. Apply the `CatalogSource` manifest:
+
[source,terminal]
----
$ oc apply -f results-*/cluster-resources/catalogSource-*.yaml
----

. Verify the catalog source is ready:
+
[source,terminal]
----
$ oc wait catalogsource -n openshift-marketplace \
  --all --for=condition=Ready --timeout=5m
----
+
.Example output
[source,text]
----
catalogsource.operators.coreos.com/rhcl-operator-catalog-<timestamp> condition met
----

[role="_additional-resources"]
.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/disconnected_environments/about-installing-oc-mirror-v2#oc-mirror-workflows-fully-disconnected-v2_about-installing-oc-mirror-v2[Mirroring an image set in a fully disconnected environment]
