// Module included in the following assemblies:
//
// *install-guide/install-guide.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-using-istio-gateway-controller-web-console_{context}"]
= Using Istio as a gateway controller

[role="_abstract"]
If you used the web console to install {prodname} and you want to use {service-mesh}, you must patch the `Subscription` custom resource (CR) to use Istio as your `Gateway` object controller.

.Prerequisites

* You are using a supported configuration of {ocp} and required components.
* You installed {prodname} using the {ocp} web console.
* You are logged into {ocp} as a cluster administrator.

.Procedure

. Patch your `Subscription` CR by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc patch subscription rhcl-operator -n _<kuadrant_system>_ --type=json -p='[{"op":"add","path":"/spec/config","value":{"env":[{"name":"ISTIO_GATEWAY_CONTROLLER_NAMES","value":"istio.io/gateway-controller"}]}}]'
----
+
Replace _<kuadrant_system>_ with the namespace you used when installing {prodname}.

. Restart your deployment to apply the updated CR by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc rollout restart deployment/kuadrant-operator-controller-manager -n _<kuadrant_system>_
----
+
Replace _<kuadrant_system>_ with the namespace you used when installing {prodname}.

.Verification

* Check the status of the `Kuadrant` CR generation by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc wait kuadrant/kuadrant --for="condition=Ready=true" -n _<kuadrant_system>_ --timeout=300s
----
+
Replace _<kuadrant_system>_ with the namespace you used when installing {prodname}.
+
.Example output
[source,terminal,subs="+quotes"]
----
kuadrant.kuadrant.io/kuadrant Ready
----
