// Module included in the following assemblies:
//
// *install-guide/install-guide.adoc

:_mod-docs-content-type: PROCEDURE
[id="install-on-ocp-cmd_{context}"]
= Installing {prodname} on {ocp} from the command line

[role="_abstract"]
You can install {product-title} with {oc-first}. You must complete these steps on each {ocp} cluster that you want to use {prodname} on.

[WARNING]
====
{prodname} uses labels formatted as `kuadrant.io/*` to search and filter resources on the cluster. Removing of any labels with the prefix might cause unexpected behavior and degradation of {prodname}.
====

.Prerequisites

* You are logged into {ocp} as a cluster administrator.
* You are using a supported configuration of {ocp} and required components.
* You installed the {oc-first}.

.Procedure

. Create the namespace where you want to install {prodname} by running the following command:
+
[source,terminal]
----
$ oc create ns <kuadrant_system>
----
+
You can replace _<kuadrant_system>_ with the namespace you want to use.

. Install {prodname} by running the following command:
+
[source,terminal]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhcl-operator
  namespace: kuadrant-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhcl-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
kind: OperatorGroup
apiVersion: operators.coreos.com/v1
metadata:
  name: kuadrant
  namespace: kuadrant-system
spec:
  upgradeStrategy: Default
EOF
----
+
Replace the value of `metatdata.namespace:` with the namespace you used.

. Confirm that the {prodname} installation is done by running one of the following commands:
+
[source,terminal]
----
$ oc wait --for=jsonpath={.status.installPlanRef.name} subscription rhcl-operator --timeout=10s
ip=$(oc get subscription rhcl-operator -o=jsonpath={.status.installPlanRef.name})
----
+
[source,bash]
----
$ oc wait --for=condition=Installed installplan ${ip} --timeout=60s
----
+
Expect the status of `installplan.operators.coreos.com/install-4rql7` when {prodname} is ready. The name of the install plan has a random suffix, in this example, `4rql7`.

. To create your {prodname} CR, enter the following command:
+
[source,bash]
----
$ oc apply -f - <<EOF
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: kuadrant-system
EOF
----

. Check the status of the {prodname} CR generation by running the following command:
+
[source,terminal]
----
$ oc wait kuadrant/kuadrant --for="condition=Ready=true" -n kuadrant-system --timeout=300s
----
+
Expect the status of `kuadrant.kuadrant.io/kuadrant condition met` when the {prodname} CR is ready.
