// Module included in the following assemblies:
//
// *install-guide/install-guide.adoc

:_mod-docs-content-type: PROCEDURE
[id="configure-dns-provider-aws_{context}"]
= Configuring DNS provider credentials for AWS

[role="_abstract"]
If you want to configure AWS DNS policies in {prodname}, you must configure the DNS credentials. You must perform the steps on each {ocp} cluster that you want to use {prodname} on.

You must configure a DNS hosted zone. The credentials for your DNS provider must have permissions to update DNS records within this zone.

.Prerequisites

* You installed {prodname} on an {ocp} cluster.
* You have access to the namespace of your gateway, for example, `api-gateway`.
+
[NOTE]
====
If you already know your environment variable values, you can create the required YAML files as required for your use case.
====

.Procedure

. Optional: Set up your environment variables as follows:

.. Assign `AWS_ACCESS_KEY_ID`, which is the key ID from AWS with Route 53 access:
+
[source,terminal]
----
$ export AWS_ACCESS_KEY_ID=xxxxxxx
----

.. Assign AWS_SECRET_ACCESS_KEY`, which is the key from AWS with Route 53 access.
+
[source,terminal]
----
$ export AWS_SECRET_ACCESS_KEY=xxxxxxx
----

.. Assign `AWS_REGION`, which is your AWS region, for example, `us-east-2` or `eu-west-1`.
+
[source,terminal]
----
$ export AWS_REGION=your-aws-region
----

. Create a `Secret` resource for your credentials as follows:
+
[source,terminal]
----
$ oc create secret generic aws-credentials \
  --namespace=api-gateway \
  --type=kuadrant.io/aws \
  --from-literal=AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  --from-literal=AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  --from-literal=AWS_REGION=$AWS_REGION
----
+
[IMPORTANT]
====
You must configure the secret in the same namespace as your gateway.
====
