// Module included in the following assemblies:
//
// *install-guide/disconnected-install.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-rhcl-disconnected-install-operators_{context}"]
= Installing {prodname} Operators

[role="_abstract"]
After you mirrored all of the {prodname} Operator bundles, you are ready to install it into your disconnected {ocp} clusters. Repeat the process as needed for each cluster that shares the registry.

.Prerequisites

* You have a supported-version, disconnected {ocp} cluster.
* You configured a mirror registry.
* You mirrored the {prodname} Operator bundles.
* Optional. You installed the `oc-mirror` CLI tool for mirroring operator catalogs.

.Procedure

. Create a namespace for {prodname} by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc new-project kuadrant-system
----
//Q: can the user change this namespace name?

. Create an `OperatorGroup` custom resource (CR) by running the following command:
+
[source,yaml,subs="+quotes"]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kuadrant-operator-group
  namespace: kuadrant-system
spec: {}
----
+
[IMPORTANT]
====
The empty `spec: {}` is required. {prodname} Operators support only the `AllNamespaces`, or cluster-scoped, install mode. Do not set the `targetNamespaces` parameter.
====
//Q: can the user change the namespace name?

. Apply the CR by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc apply -f kuadrant-operator-group.yaml
----

. Query the default channel from the `PackageManifest` by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ CHANNEL=$(oc get packagemanifest kuadrant-operator -n openshift-marketplace \
  -o jsonpath='{.status.defaultChannel}')
----

. Create a `Subscription` resource by running the following command:
+
[source,yaml,subs="+quotes"]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: kuadrant-system
spec:
  channel: ${CHANNEL}
  name: kuadrant-operator
  source: kuadrant-disconnected-catalog
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
----
+
[NOTE]
====
Replace the `spec.source` parameter value with the `CatalogSource` name from `oc-mirror` if it differs. OLM automatically installs the Authorino, Limitador, and DNS Operators based on the dependencies declared in the {prodname} Operator bundle.
====
//Q: don't know what this means; better to show an actual example from the previous step to this one

. Apply the CR by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc apply -f kuadrant-operator.yaml
----

. Verify that all Operator `ClusterServiceVersion` resources are installed by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc get csv -n kuadrant-system
----
+
.Example output
[source,text]
----
NAME                           DISPLAY                  VERSION   REPLACES   PHASE
kuadrant-operator.vX.Y.Z       Kuadrant Operator        X.Y.Z                Succeeded
authorino-operator.vX.Y.Z      Authorino Operator       X.Y.Z                Succeeded
limitador-operator.vX.Y.Z      Limitador Operator       X.Y.Z                Succeeded
dns-operator.vX.Y.Z            DNS Operator             X.Y.Z                Succeeded
----

. Verify that all pods are running by using the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc get pods -n kuadrant-system
----

. Create a `Kuadrant` custom resource (CR) by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ cat <<EOF | oc apply -f -
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: kuadrant-system
spec: {}
EOF
----

. Wait for the `Kuadrant` resource to be ready by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc wait kuadrant/kuadrant -n kuadrant-system --for=condition=Ready --timeout=5m
----

.Verification

. Verify that all pods are running by using the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc get pods -n kuadrant-system
----
+
All pods should show `Running` status.

. Verify that there are no image pull errors by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc get events -n kuadrant-system --field-selector reason=Failed
----
+
The output should show no image pull failures.
+
[NOTE]
====
Pod specifications still show original image references, for example, `quay.io/kuadrant/...`, even when images are pulled from your mirror registry. The redirection happens transparently at the CRI-O level through `ImageDigestMirrorSet` or `ImageTagMirrorSet` configuration objects.
====
