// Module included in the following assemblies:
//
// *release-notes/release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="rhcl-relnotes-dev-preview_{context}"]
= Developer Preview features

[role="_abstract"]
Developer Preview features are included in {prodname} {version}.

[IMPORTANT]
====
Developer Preview features are not supported by {rh} in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features give you early access to functionality in advance of possible inclusion in a {rh} product offering. Customers can use these features to test functionality and give feedback during the development process.

Developer Preview features might not have any documentation, are subject to change or removal at any time, and have received limited testing. {rh} might provide ways to submit feedback on Developer Preview features without an associated SLA. For more information, see link:https://access.redhat.com/support/offerings/devpreview[{rh} Developer Preview - Scope of Support].
====

{rh} customers can give feedback on Developer Preview features through your account teams. You can also ask questions and give feedback directly by using the link:https://docs.google.com/forms/d/e/1FAIpQLSfrbEYkqfTMs_KBYPuM2UlVZ9Ld9_E8mcQi4xkBFzFQlnZNRw/viewform[Connectivity Link contact form] or by emailing mailto:rhcl-contactus@redhat.com[rhcl-contactus@redhat.com].

[id="rhcl-relnotes-tp-coredns_{context}"]
== CoreDNS integration for on-premise DNS

{prodname} provides integration with link:https://coredns.io/[CoreDNS] for on-premise DNS as a Developer Preview feature. For more information, see the link:https://github.com/Kuadrant/kuadrant-operator/blob/main/doc/user-guides/dns/core-dns.md[Kuadrant documentation on using CoreDNS].
