// Module included in the following assemblies:
//
// *deployment/deployment.adoc

:_mod-docs-content-type: REFERENCE
[id="ref-coredns-corefile-config_{context}"]
= CoreDNS Corefile configuration reference

[role="_abstract"]
In {ocp}, the DNS Operator stores and updates the configuration from a CoreDND Corefile in a ConfigMap.

You can view your current Corefile contents by checking the ConfigMap by running the following command:
[source,terminal]
----
$ oc get configmap/dns-default -n openshift-dns -o yaml
----

After updating the ConfigMap through the DNS Operator, restart CoreDNS by using the following command:
[source,terminal]
----
$ oc -n kuadrant-coredns rollout restart deployment kuadrant-coredns
----

A Corefile is organized into server blocks that define how DNS queries are handled based on the port and zone. Plugin execution order is determined at build time, not by Corefile order, so you can list plugins in any order. When making configurations by using the DNS Operator, you can check the ConfigMap for the resulting server block.

.Example Corefile
[source,text]
----
k.example.com
    debug
    errors
    log
    health {
        lameduck 5s
    }
    ready
    geoip GeoLite2-City-demo.mmdb {
        edns-subnet
    }
    metadata
    transfer {
        to *
    }
    kuadrant
    prometheus 0.0.0.0:9153
}
----

Zone Coordination::
Each zone in the Corefile must match a zone listed in your CoreDNS provider secret's `ZONES` field.

Required Plugins::
The `geoip` and `metadata` plugins are included by default with the {prodname} implementation of the CoreDNS Corefile.

//Q: do we need to edit or patch DNS Operator objects to make changes to a corefile? something like https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/networking_operators/dns-operator#nw-dns-cache-tuning_dns-operator or https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/networking_operators/dns-operator#nw-dns-operatorloglevel_dns-operator?
