// Module included in the following assemblies:
//
// *observability/observability.adoc

:_mod-docs-content-type: REFERENCE
[id="rhcl-about-import-dashboard-auto-ocp_{context}"]
= Importing dashboards automatically in {ocp}

[role="_abstract"]
As an infrastructure engineer, automating the import of observability dashboards can give you more consistency, version control, and operational velocity. Automation gives you the benefits of monitoring-as-code, and helps keep Operators updated, clusters identical, and supports multi-tenancy.

//Q: is this method the actual happy path for customers? or should we use kiali?
* You can use a `GrafanaDashboard` resource to reference a `ConfigMap`. For an example, see https://grafana.github.io/grafana-operator/docs/examples/dashboard_from_configmap/readme/[Dashboard from ConfigMap in the Grafana documentation].
+
Data sources are configured as template variables, automatically integrating with your existing data sources. The metrics for these dashboards are sourced from Prometheus.
+
[IMPORTANT]
====
For some example dashboard panels to work correctly, HTTPRoutes in {prodname} must include a `service` and `deployment` label with a value that matches the name of the service and deployment being routed to. For example, `service=my-app` and `deployment=my-app`. This allows low-level Istio and Envoy metrics to be joined with Gateway API state metrics.
====

* You can automate dashboard provisioning in Grafana by adding JSON files to a `ConfigMap` that you must mount at `/etc/grafana/provisioning/dashboards`.
//Q: if it kinda stinks to do it this way, why do we even list it? is there a scenario where this method is required?
