// Module included in the following assemblies:
//
// *release-notes/release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="rhcl-relnotes-tech-preview_{context}"]
= Technology Preview features

[role="_abstract"]
You can try the Technology Preview features that are available with {product-title} {version}.

[IMPORTANT]
====
Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. {rh} does not recommend using them in production.

Technology Preview features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information, see https://access.redhat.com/support/offerings/techpreview[{rh} Technology Preview Features - Scope of Support].
====

[id="rhcl-relnotes-tp-coredns_{context}"]
== CoreDNS integration for on-premise DNS

{prodname} provides integration with link:https://coredns.io/[CoreDNS] for on-premise DNS as a Technology Preview feature. For more information, see the link:https://docs.redhat.com/en/documentation/red_hat_connectivity_link/1.2/html/configuring_and_deploying_gateway_policies_with_connectivity_link/proc-configure-onprem-dns_rhcl[Configure on-premise DNS with CoreDNS (Technology Preview)].
